name: Daily Run

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.2'

    - name: Send notification
      env:
        MINIFLUX_URL: ${{ secrets.MINIFLUX_URL }}
        MINIFLUX_TOKEN: ${{ secrets.MINIFLUX_TOKEN }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        CATEGORY: daily
        RECEIVER_EMAIL: contact@skatkov.com
        CGO_ENABLED: 0
      run: |
        go run main.go
