name: Daily Run

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: latest

    - name: Run application
      env:
        MINIFLUX_URL: ${{ secrets.MINIFLUX_URL }}
        MINIFLUX_USER: ${{ secrets.MINIFLUX_USER }}
        MINIFLUX_PASS: ${{ secrets.MINIFLUX_PASS }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        CATEGORY: ${{ variables.CATEGORY }}
        RECEIVER_EMAIL: ${{ variables.RECEIVER_EMAIL }}}
        CGO_ENABLED: 0
      run: |
        go run main.go
