name: Runner

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.2'

    - name: Check RSS updates and send them over email.
      env:
        MINIFLUX_URL: "https://reader.miniflux.app/v1/"
        MINIFLUX_TOKEN: ${{ secrets.b3B6BNLMh6Da9OMqMOgge6nq1j1TNKTaVKtpcmekLxA= }}
        SMTP_USERNAME: ${{ secrets.towner@towner.blog }}
        SMTP_PASSWORD: ${{ secrets.XfF3kQnx2%w&wA }}
        SEND_TO: ${{ secrets.hey@shawntowner.com }}
        CGO_ENABLED: 0
        # CATEGORY: All
        LIMIT: 5
      run: |
        go run main.go
